/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AdminDashboard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminDashboard__factory>;
    getContractFactory(
      name: "AttendanceManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AttendanceManager__factory>;
    getContractFactory(
      name: "EmployeeDashboard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmployeeDashboard__factory>;
    getContractFactory(
      name: "EmployerDashboard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmployerDashboard__factory>;
    getContractFactory(
      name: "SalaryContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SalaryContract__factory>;
    getContractFactory(
      name: "SalaryStreamingFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SalaryStreamingFactory__factory>;

    getContractAt(
      name: "AdminDashboard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminDashboard>;
    getContractAt(
      name: "AttendanceManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AttendanceManager>;
    getContractAt(
      name: "EmployeeDashboard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmployeeDashboard>;
    getContractAt(
      name: "EmployerDashboard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmployerDashboard>;
    getContractAt(
      name: "SalaryContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SalaryContract>;
    getContractAt(
      name: "SalaryStreamingFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SalaryStreamingFactory>;

    deployContract(
      name: "AdminDashboard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminDashboard>;
    deployContract(
      name: "AttendanceManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AttendanceManager>;
    deployContract(
      name: "EmployeeDashboard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployeeDashboard>;
    deployContract(
      name: "EmployerDashboard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployerDashboard>;
    deployContract(
      name: "SalaryContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SalaryContract>;
    deployContract(
      name: "SalaryStreamingFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SalaryStreamingFactory>;

    deployContract(
      name: "AdminDashboard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminDashboard>;
    deployContract(
      name: "AttendanceManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AttendanceManager>;
    deployContract(
      name: "EmployeeDashboard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployeeDashboard>;
    deployContract(
      name: "EmployerDashboard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployerDashboard>;
    deployContract(
      name: "SalaryContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SalaryContract>;
    deployContract(
      name: "SalaryStreamingFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SalaryStreamingFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
